apiVersion: apps/v1
kind: Deployment
metadata:
  name: byodc
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.byodc.config.replicas }}
  selector:
    matchLabels:
      app: byodc
  template:
    metadata:
      labels:
        app: byodc
    spec:
      {{- if .Values.byodc.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.byodc.image.pullSecret }}
      {{- end }}
      {{- with .Values.byodc.config.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: byodc
          {{- if .Values.local }}
          imagePullPolicy: IfNotPresent
          {{- else }}
          imagePullPolicy: Always
          {{- end }}
          image: {{ .Values.byodc.image.name }}:{{ .Values.byodc.image.tag }}
          resources:
            limits:
            {{- range $key, $value := .Values.byodc.config.limits }}
              {{ $key }}: {{ $value }}
            {{- end }}
          ports:
            - containerPort: 80
            - containerPort: 8080
          env:
            - name: Redis__ConnectionString
              value: {{ tpl .Values.byodc.config.redis.host . }}:{{ .Values.byodc.config.redis.port }}
            - name: Redis__Channel
              value: {{ .Values.byodc.config.redis.channel }}
              {{- with .Values.byodc.config.applicationInsights }}
                {{- if .instrumentationKey }}
            - name: ApplicationInsights__InstrumentationKey
              value: {{ .instrumentationKey }}
                {{- end }}
              {{- end }}
            - name: Logging__LogLevel__Default
              value: {{ .Values.byodc.config.logLevel }}
            - name: PosApi__BaseUrl
              value: {{ .Values.byodc.config.posApi.baseUrl }}
            - name: Helipad__BaseUrl
              value: {{ .Values.byodc.config.helipad.baseUrl }}
              {{- with .Values.byodc.proxy }}
                {{- if kindIs "string" . }}
            - name: Proxy
              value: {{ . | quote }}
                {{- else if kindIs "map" . }}
                  {{- range $key, $value := . }}
                    {{- if $value }}
            - name: {{ $key | upper }}_PROXY
              value: {{ $value | quote }}
                    {{- end }}
                  {{- end }}
                {{- end }}
              {{- end }}
              {{- with .Values.byodc.config.env }}
                {{- range $value := . }}
                  {{- if $value }}
            - {{ toYaml $value | nindent 14 | trim -}}
                  {{- end }}
                {{- end }}
              {{- end }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /health/ready
              port: 80
            failureThreshold: 30
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: byodc
  namespace: {{ .Release.Namespace }}
  labels:
    app: byodc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: prometheus
      port: 8080
      targetPort: 8080
  selector:
    app: byodc
